// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClickBook.proto

package net.spright.theater.protos;

public final class ClickBookProtos {
  private ClickBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClickOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // optional int64 count = 2 [default = 0];
    /**
     * <code>optional int64 count = 2 [default = 0];</code>
     */
    boolean hasCount();
    /**
     * <code>optional int64 count = 2 [default = 0];</code>
     */
    long getCount();

    // optional bool favorite = 3 [default = false];
    /**
     * <code>optional bool favorite = 3 [default = false];</code>
     */
    boolean hasFavorite();
    /**
     * <code>optional bool favorite = 3 [default = false];</code>
     */
    boolean getFavorite();
  }
  /**
   * Protobuf type {@code protos.Click}
   */
  public static final class Click extends
      com.google.protobuf.GeneratedMessage
      implements ClickOrBuilder {
    // Use Click.newBuilder() to construct.
    private Click(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Click(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Click defaultInstance;
    public static Click getDefaultInstance() {
      return defaultInstance;
    }

    public Click getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Click(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              count_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              favorite_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.spright.theater.protos.ClickBookProtos.internal_static_protos_Click_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.spright.theater.protos.ClickBookProtos.internal_static_protos_Click_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.spright.theater.protos.ClickBookProtos.Click.class, net.spright.theater.protos.ClickBookProtos.Click.Builder.class);
    }

    public static com.google.protobuf.Parser<Click> PARSER =
        new com.google.protobuf.AbstractParser<Click>() {
      public Click parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Click(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Click> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 count = 2 [default = 0];
    public static final int COUNT_FIELD_NUMBER = 2;
    private long count_;
    /**
     * <code>optional int64 count = 2 [default = 0];</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 count = 2 [default = 0];</code>
     */
    public long getCount() {
      return count_;
    }

    // optional bool favorite = 3 [default = false];
    public static final int FAVORITE_FIELD_NUMBER = 3;
    private boolean favorite_;
    /**
     * <code>optional bool favorite = 3 [default = false];</code>
     */
    public boolean hasFavorite() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool favorite = 3 [default = false];</code>
     */
    public boolean getFavorite() {
      return favorite_;
    }

    private void initFields() {
      id_ = "";
      count_ = 0L;
      favorite_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, count_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, favorite_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, count_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, favorite_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.spright.theater.protos.ClickBookProtos.Click parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.spright.theater.protos.ClickBookProtos.Click parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.spright.theater.protos.ClickBookProtos.Click parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.spright.theater.protos.ClickBookProtos.Click parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.spright.theater.protos.ClickBookProtos.Click parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.spright.theater.protos.ClickBookProtos.Click parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.spright.theater.protos.ClickBookProtos.Click parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.spright.theater.protos.ClickBookProtos.Click parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.spright.theater.protos.ClickBookProtos.Click parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.spright.theater.protos.ClickBookProtos.Click parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.spright.theater.protos.ClickBookProtos.Click prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.Click}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.spright.theater.protos.ClickBookProtos.ClickOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.spright.theater.protos.ClickBookProtos.internal_static_protos_Click_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.spright.theater.protos.ClickBookProtos.internal_static_protos_Click_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.spright.theater.protos.ClickBookProtos.Click.class, net.spright.theater.protos.ClickBookProtos.Click.Builder.class);
      }

      // Construct using net.spright.theater.protos.ClickBookProtos.Click.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        favorite_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.spright.theater.protos.ClickBookProtos.internal_static_protos_Click_descriptor;
      }

      public net.spright.theater.protos.ClickBookProtos.Click getDefaultInstanceForType() {
        return net.spright.theater.protos.ClickBookProtos.Click.getDefaultInstance();
      }

      public net.spright.theater.protos.ClickBookProtos.Click build() {
        net.spright.theater.protos.ClickBookProtos.Click result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.spright.theater.protos.ClickBookProtos.Click buildPartial() {
        net.spright.theater.protos.ClickBookProtos.Click result = new net.spright.theater.protos.ClickBookProtos.Click(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.count_ = count_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.favorite_ = favorite_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.spright.theater.protos.ClickBookProtos.Click) {
          return mergeFrom((net.spright.theater.protos.ClickBookProtos.Click)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.spright.theater.protos.ClickBookProtos.Click other) {
        if (other == net.spright.theater.protos.ClickBookProtos.Click.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasFavorite()) {
          setFavorite(other.getFavorite());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.spright.theater.protos.ClickBookProtos.Click parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.spright.theater.protos.ClickBookProtos.Click) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // optional int64 count = 2 [default = 0];
      private long count_ ;
      /**
       * <code>optional int64 count = 2 [default = 0];</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 count = 2 [default = 0];</code>
       */
      public long getCount() {
        return count_;
      }
      /**
       * <code>optional int64 count = 2 [default = 0];</code>
       */
      public Builder setCount(long value) {
        bitField0_ |= 0x00000002;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 count = 2 [default = 0];</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0L;
        onChanged();
        return this;
      }

      // optional bool favorite = 3 [default = false];
      private boolean favorite_ ;
      /**
       * <code>optional bool favorite = 3 [default = false];</code>
       */
      public boolean hasFavorite() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool favorite = 3 [default = false];</code>
       */
      public boolean getFavorite() {
        return favorite_;
      }
      /**
       * <code>optional bool favorite = 3 [default = false];</code>
       */
      public Builder setFavorite(boolean value) {
        bitField0_ |= 0x00000004;
        favorite_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool favorite = 3 [default = false];</code>
       */
      public Builder clearFavorite() {
        bitField0_ = (bitField0_ & ~0x00000004);
        favorite_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protos.Click)
    }

    static {
      defaultInstance = new Click(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protos.Click)
  }

  public interface ClickBookOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .protos.Click click = 1;
    /**
     * <code>repeated .protos.Click click = 1;</code>
     */
    java.util.List<net.spright.theater.protos.ClickBookProtos.Click> 
        getClickList();
    /**
     * <code>repeated .protos.Click click = 1;</code>
     */
    net.spright.theater.protos.ClickBookProtos.Click getClick(int index);
    /**
     * <code>repeated .protos.Click click = 1;</code>
     */
    int getClickCount();
    /**
     * <code>repeated .protos.Click click = 1;</code>
     */
    java.util.List<? extends net.spright.theater.protos.ClickBookProtos.ClickOrBuilder> 
        getClickOrBuilderList();
    /**
     * <code>repeated .protos.Click click = 1;</code>
     */
    net.spright.theater.protos.ClickBookProtos.ClickOrBuilder getClickOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protos.ClickBook}
   */
  public static final class ClickBook extends
      com.google.protobuf.GeneratedMessage
      implements ClickBookOrBuilder {
    // Use ClickBook.newBuilder() to construct.
    private ClickBook(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClickBook(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClickBook defaultInstance;
    public static ClickBook getDefaultInstance() {
      return defaultInstance;
    }

    public ClickBook getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClickBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                click_ = new java.util.ArrayList<net.spright.theater.protos.ClickBookProtos.Click>();
                mutable_bitField0_ |= 0x00000001;
              }
              click_.add(input.readMessage(net.spright.theater.protos.ClickBookProtos.Click.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          click_ = java.util.Collections.unmodifiableList(click_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.spright.theater.protos.ClickBookProtos.internal_static_protos_ClickBook_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.spright.theater.protos.ClickBookProtos.internal_static_protos_ClickBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.spright.theater.protos.ClickBookProtos.ClickBook.class, net.spright.theater.protos.ClickBookProtos.ClickBook.Builder.class);
    }

    public static com.google.protobuf.Parser<ClickBook> PARSER =
        new com.google.protobuf.AbstractParser<ClickBook>() {
      public ClickBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClickBook(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClickBook> getParserForType() {
      return PARSER;
    }

    // repeated .protos.Click click = 1;
    public static final int CLICK_FIELD_NUMBER = 1;
    private java.util.List<net.spright.theater.protos.ClickBookProtos.Click> click_;
    /**
     * <code>repeated .protos.Click click = 1;</code>
     */
    public java.util.List<net.spright.theater.protos.ClickBookProtos.Click> getClickList() {
      return click_;
    }
    /**
     * <code>repeated .protos.Click click = 1;</code>
     */
    public java.util.List<? extends net.spright.theater.protos.ClickBookProtos.ClickOrBuilder> 
        getClickOrBuilderList() {
      return click_;
    }
    /**
     * <code>repeated .protos.Click click = 1;</code>
     */
    public int getClickCount() {
      return click_.size();
    }
    /**
     * <code>repeated .protos.Click click = 1;</code>
     */
    public net.spright.theater.protos.ClickBookProtos.Click getClick(int index) {
      return click_.get(index);
    }
    /**
     * <code>repeated .protos.Click click = 1;</code>
     */
    public net.spright.theater.protos.ClickBookProtos.ClickOrBuilder getClickOrBuilder(
        int index) {
      return click_.get(index);
    }

    private void initFields() {
      click_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getClickCount(); i++) {
        if (!getClick(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < click_.size(); i++) {
        output.writeMessage(1, click_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < click_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, click_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.spright.theater.protos.ClickBookProtos.ClickBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.spright.theater.protos.ClickBookProtos.ClickBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.spright.theater.protos.ClickBookProtos.ClickBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.spright.theater.protos.ClickBookProtos.ClickBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.spright.theater.protos.ClickBookProtos.ClickBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.spright.theater.protos.ClickBookProtos.ClickBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.spright.theater.protos.ClickBookProtos.ClickBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.spright.theater.protos.ClickBookProtos.ClickBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.spright.theater.protos.ClickBookProtos.ClickBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.spright.theater.protos.ClickBookProtos.ClickBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.spright.theater.protos.ClickBookProtos.ClickBook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.ClickBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.spright.theater.protos.ClickBookProtos.ClickBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.spright.theater.protos.ClickBookProtos.internal_static_protos_ClickBook_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.spright.theater.protos.ClickBookProtos.internal_static_protos_ClickBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.spright.theater.protos.ClickBookProtos.ClickBook.class, net.spright.theater.protos.ClickBookProtos.ClickBook.Builder.class);
      }

      // Construct using net.spright.theater.protos.ClickBookProtos.ClickBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getClickFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (clickBuilder_ == null) {
          click_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          clickBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.spright.theater.protos.ClickBookProtos.internal_static_protos_ClickBook_descriptor;
      }

      public net.spright.theater.protos.ClickBookProtos.ClickBook getDefaultInstanceForType() {
        return net.spright.theater.protos.ClickBookProtos.ClickBook.getDefaultInstance();
      }

      public net.spright.theater.protos.ClickBookProtos.ClickBook build() {
        net.spright.theater.protos.ClickBookProtos.ClickBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.spright.theater.protos.ClickBookProtos.ClickBook buildPartial() {
        net.spright.theater.protos.ClickBookProtos.ClickBook result = new net.spright.theater.protos.ClickBookProtos.ClickBook(this);
        int from_bitField0_ = bitField0_;
        if (clickBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            click_ = java.util.Collections.unmodifiableList(click_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.click_ = click_;
        } else {
          result.click_ = clickBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.spright.theater.protos.ClickBookProtos.ClickBook) {
          return mergeFrom((net.spright.theater.protos.ClickBookProtos.ClickBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.spright.theater.protos.ClickBookProtos.ClickBook other) {
        if (other == net.spright.theater.protos.ClickBookProtos.ClickBook.getDefaultInstance()) return this;
        if (clickBuilder_ == null) {
          if (!other.click_.isEmpty()) {
            if (click_.isEmpty()) {
              click_ = other.click_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureClickIsMutable();
              click_.addAll(other.click_);
            }
            onChanged();
          }
        } else {
          if (!other.click_.isEmpty()) {
            if (clickBuilder_.isEmpty()) {
              clickBuilder_.dispose();
              clickBuilder_ = null;
              click_ = other.click_;
              bitField0_ = (bitField0_ & ~0x00000001);
              clickBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getClickFieldBuilder() : null;
            } else {
              clickBuilder_.addAllMessages(other.click_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getClickCount(); i++) {
          if (!getClick(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.spright.theater.protos.ClickBookProtos.ClickBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.spright.theater.protos.ClickBookProtos.ClickBook) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .protos.Click click = 1;
      private java.util.List<net.spright.theater.protos.ClickBookProtos.Click> click_ =
        java.util.Collections.emptyList();
      private void ensureClickIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          click_ = new java.util.ArrayList<net.spright.theater.protos.ClickBookProtos.Click>(click_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          net.spright.theater.protos.ClickBookProtos.Click, net.spright.theater.protos.ClickBookProtos.Click.Builder, net.spright.theater.protos.ClickBookProtos.ClickOrBuilder> clickBuilder_;

      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public java.util.List<net.spright.theater.protos.ClickBookProtos.Click> getClickList() {
        if (clickBuilder_ == null) {
          return java.util.Collections.unmodifiableList(click_);
        } else {
          return clickBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public int getClickCount() {
        if (clickBuilder_ == null) {
          return click_.size();
        } else {
          return clickBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public net.spright.theater.protos.ClickBookProtos.Click getClick(int index) {
        if (clickBuilder_ == null) {
          return click_.get(index);
        } else {
          return clickBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public Builder setClick(
          int index, net.spright.theater.protos.ClickBookProtos.Click value) {
        if (clickBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClickIsMutable();
          click_.set(index, value);
          onChanged();
        } else {
          clickBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public Builder setClick(
          int index, net.spright.theater.protos.ClickBookProtos.Click.Builder builderForValue) {
        if (clickBuilder_ == null) {
          ensureClickIsMutable();
          click_.set(index, builderForValue.build());
          onChanged();
        } else {
          clickBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public Builder addClick(net.spright.theater.protos.ClickBookProtos.Click value) {
        if (clickBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClickIsMutable();
          click_.add(value);
          onChanged();
        } else {
          clickBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public Builder addClick(
          int index, net.spright.theater.protos.ClickBookProtos.Click value) {
        if (clickBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClickIsMutable();
          click_.add(index, value);
          onChanged();
        } else {
          clickBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public Builder addClick(
          net.spright.theater.protos.ClickBookProtos.Click.Builder builderForValue) {
        if (clickBuilder_ == null) {
          ensureClickIsMutable();
          click_.add(builderForValue.build());
          onChanged();
        } else {
          clickBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public Builder addClick(
          int index, net.spright.theater.protos.ClickBookProtos.Click.Builder builderForValue) {
        if (clickBuilder_ == null) {
          ensureClickIsMutable();
          click_.add(index, builderForValue.build());
          onChanged();
        } else {
          clickBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public Builder addAllClick(
          java.lang.Iterable<? extends net.spright.theater.protos.ClickBookProtos.Click> values) {
        if (clickBuilder_ == null) {
          ensureClickIsMutable();
          super.addAll(values, click_);
          onChanged();
        } else {
          clickBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public Builder clearClick() {
        if (clickBuilder_ == null) {
          click_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          clickBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public Builder removeClick(int index) {
        if (clickBuilder_ == null) {
          ensureClickIsMutable();
          click_.remove(index);
          onChanged();
        } else {
          clickBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public net.spright.theater.protos.ClickBookProtos.Click.Builder getClickBuilder(
          int index) {
        return getClickFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public net.spright.theater.protos.ClickBookProtos.ClickOrBuilder getClickOrBuilder(
          int index) {
        if (clickBuilder_ == null) {
          return click_.get(index);  } else {
          return clickBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public java.util.List<? extends net.spright.theater.protos.ClickBookProtos.ClickOrBuilder> 
           getClickOrBuilderList() {
        if (clickBuilder_ != null) {
          return clickBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(click_);
        }
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public net.spright.theater.protos.ClickBookProtos.Click.Builder addClickBuilder() {
        return getClickFieldBuilder().addBuilder(
            net.spright.theater.protos.ClickBookProtos.Click.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public net.spright.theater.protos.ClickBookProtos.Click.Builder addClickBuilder(
          int index) {
        return getClickFieldBuilder().addBuilder(
            index, net.spright.theater.protos.ClickBookProtos.Click.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.Click click = 1;</code>
       */
      public java.util.List<net.spright.theater.protos.ClickBookProtos.Click.Builder> 
           getClickBuilderList() {
        return getClickFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.spright.theater.protos.ClickBookProtos.Click, net.spright.theater.protos.ClickBookProtos.Click.Builder, net.spright.theater.protos.ClickBookProtos.ClickOrBuilder> 
          getClickFieldBuilder() {
        if (clickBuilder_ == null) {
          clickBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.spright.theater.protos.ClickBookProtos.Click, net.spright.theater.protos.ClickBookProtos.Click.Builder, net.spright.theater.protos.ClickBookProtos.ClickOrBuilder>(
                  click_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          click_ = null;
        }
        return clickBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protos.ClickBook)
    }

    static {
      defaultInstance = new ClickBook(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protos.ClickBook)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_Click_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_Click_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_ClickBook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_ClickBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ClickBook.proto\022\006protos\">\n\005Click\022\n\n\002id" +
      "\030\001 \002(\t\022\020\n\005count\030\002 \001(\003:\0010\022\027\n\010favorite\030\003 \001" +
      "(\010:\005false\")\n\tClickBook\022\034\n\005click\030\001 \003(\0132\r." +
      "protos.ClickB-\n\032net.spright.theater.prot" +
      "osB\017ClickBookProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protos_Click_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protos_Click_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protos_Click_descriptor,
              new java.lang.String[] { "Id", "Count", "Favorite", });
          internal_static_protos_ClickBook_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protos_ClickBook_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protos_ClickBook_descriptor,
              new java.lang.String[] { "Click", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
